[package]
name = "kaminari"
version = "0.8.1"
edition = "2021"
authors = ["zephyr <i@zephyr.moe>"]
keywords = ["lightws", "network"]
repository = "https://github.com/zephyrchien/kaminari"
documentation = "https://docs.rs/kaminari"
description = "The ever fast websocket tunnel built on top of lightws."
license = "MIT"

[dependencies]
lightws = { version = "0.6.4", features = ["unsafe_auto_mask_write"] }
udpflow = "0.1.0"
tokio = "1"
tokio-rustls = { version = "0.23.3", features = ["early-data", "dangerous_configuration"] }
webpki-roots = "0.22.3"
rustls-pemfile = "1"
rcgen = "0.9"
lazy_static = "1.4.0"
