[package]
name = "kaminari"
version = "0.9.1"
edition = "2021"
authors = ["zephyr <i@zephyr.moe>"]
keywords = ["lightws", "network"]
repository = "https://github.com/zephyrchien/kaminari"
documentation = "https://docs.rs/kaminari"
description = "The ever fast websocket tunnel built on top of lightws."
license = "MIT"

[features]
default = []
all = ["ws", "uot", "tls", "mix"]
mix = ["ws", "tls"]
ws = ["lightws"]
uot = ["udpflow"]
tls = ["tokio-rustls", "webpki-roots", "rustls-pemfile", "rcgen"]


[dependencies]
# async rt
tokio = "1.9"

# global static
lazy_static = "1"

# ws
lightws = { version = "0.6.5", features = ["unsafe_auto_mask_write"], optional = true }

# uot
udpflow = { version = "0.1.0", optional = true }

# tls
tokio-rustls = { version = "0.23.3", features = ["early-data", "dangerous_configuration"], optional = true }
webpki-roots = { version = "0.22.3", optional = true }
rustls-pemfile = { version = "1", optional = true }
rcgen = {version = "0.9", optional = true }

[package.metadata.docs.rs]
all-features = true
