[package]
name = "kaminari-cmd"
version = "0.5.6"
edition = "2021"
authors = ["zephyr <i@zephyr.moe>"]
repository = "https://github.com/zephyrchien/kaminari/cmd"
description = "The ever fast websocket tunnel built on top of lightws."
readme = "README.md"
license = "GPL-3.0"

[dependencies]
anyhow = "1"
realm_io = "0.3.2"
kaminari = { version = "0.9.2", features = ["ws", "tls"] }
tokio = { version = "1.9", features = ["rt", "net", "macros"] }

[[bin]]
name = "kaminaric"
path = "src/client.rs"

[[bin]]
name = "kaminaris"
path = "src/server.rs"
