[package]
name = "kaminari-cmd"
version = "0.4.0"
edition = "2021"
authors = ["zephyr <i@zephyr.moe>"]
repository = "https://github.com/zephyrchien/kaminari/cmd"
description = "The ever fast websocket tunnel built on top of lightws."
readme = "README.md"
license = "GPL-3.0"

[dependencies]
kaminari = "0.5.3"
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread", "io-util"] }
anyhow = "1"

[[bin]]
name = "kaminaric"
path = "src/client.rs"

[[bin]]
name = "kaminaris"
path = "src/server.rs"
